#!/usr/bin/env ruby
loc = Dir.pwd

def rand_pkmn
  "#{__dir__}/orig_151/#{Dir.entries(__dir__ + "/orig_151").sample}"
end

def set_icon(pkmn)
  "#{__dir__}/fileicon set #{ARGV[0]} #{pkmn}"
end

def choose_pkmn
  # If number flag is passed & valid, use that pkmn, else random
  if ARGV[1]
    num = ARGV[1].gsub('-', '')
    Dir.entries(__dir__ + "/orig_151").include?("#{num}.png") ? "#{__dir__}/orig_151/#{num}.png" : rand_pkmn
  else
    rand_pkmn
  end
end

# If dir does not exist, create it, if it exists, prompt to update icon
response = `mkdir #{loc + "/" + ARGV[0]} 2>&1`
if response == ''
  `#{set_icon(choose_pkmn)}`
elsif response.include? 'File exists'
  puts "Change icon for existsing file or directory - #{ARGV[0]} ? [Yn]"
  if STDIN.gets.chomp.downcase == 'y'
    if !`#{__dir__}/fileicon test #{ARGV[0]} 2>&1`.include?('NO')
      `#{__dir__}/fileicon rm #{ARGV[0]}`
    end
    `#{set_icon(choose_pkmn)}`
  end
else
  puts 'The wild pokémon got away!'
end
